version: "2.1"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      #- PLEX_CLAIM= #optional
      #- TZ=<timezone>
      - PLEX_CLAIM=claim-TPrWsTMwsQzmQZxnPnj-
      #- ADVERTISE_IP=http://192.168.1.6:32400/
    volumes:
      - /d/docker/plex/library:/config
      - /d/docker/plex/tvseries:/tv
      - /d/docker/plex/movies:/movies
    restart: unless-stopped
    ports:
        - 32400:32400/tcp
        - 3005:3005/tcp
        - 8324:8324/tcp
        - 32469:32469/tcp
        - 1900:1900/udp
        - 32410:32410/udp
        - 32412:32412/udp
        - 32413:32413/udp
        - 32414:32414/udp    